config/routes.rb
Rails.application.routes.draw do
  
  get 'user_exam_questions/index'

  get 'user_exam_controller/index'

  resources :user_exams
  mount Ckeditor::Engine => '/ckeditor'
  get 'users/index'

  devise_for :users
  resources :question_types
  resources :answers
  resources :organizers
  resources :institutions
  resources :categories
  resources :areas
  resources :mocks
  resources :mocks do
    resources :exams, except: :index
  end
  
  resources :user_exam do 
    resources :user_exam_questions
  end
  
  
  resources :exams, except: :index
  resources :exams, except: :index do
    resources :questions
  end
  resources :questions do
    resources :helper_objects
    resources :alternatives, except: :index
  end
  resources :helper_objects

  root 'mocks#index'

  match '/users',   to: 'users#index',   via: 'get'
  
  get "user_exam_question/new_custom_question" => 'user_exam_question#new_custom_question', :as => :new_custom_question
  

end

app/models/alternative.rb
class Alternative < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  do_not_validate_attachment_file_type :image
  
  
  # corrigir o erro de validacao de tipo de imagens pois nao esta amigavel ao usuario.
  validates_attachment :image, content_type: { content_type: "image/jpeg" } if present?
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :alternative
end

app/models/area.rb
class Area < ActiveRecord::Base
    has_many :mocks
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :mocks
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  belongs_to :mock
  has_many :questions, dependent: :destroy
end

app/models/helper_object.rb
class HelperObject < ActiveRecord::Base
  
  # referencias
  belongs_to :question
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  do_not_validate_attachment_file_type :image
  
  
  # corrigir o erro de validacao de tipo de imagens pois nao esta amigavel ao usuario.
  validates_attachment :image, content_type: { content_type: "image/jpeg" } if present?
  
end

app/models/institution.rb
class Institution < ActiveRecord::Base
    has_many :mocks
end

app/models/mock.rb
class Mock < ActiveRecord::Base
  belongs_to :institution
  belongs_to :organizer
  belongs_to :category
  belongs_to :area
  has_many :exams, dependent: :destroy
end

app/models/organizer.rb
class Organizer < ActiveRecord::Base
    has_many :mocks
end

app/models/question.rb
class Question < ActiveRecord::Base
  
  # referencias
  belongs_to :exam
  belongs_to :question_type
  has_many :helper_objects, dependent: :destroy
  has_many :alternatives, dependent: :destroy
  has_many :user_exam_questions, dependent: :destroy
  has_many :user_exam, through: :user_exam_questions
  
  validates :number, :exam_id, :veracity, :question_type_id, presence: true

end

app/models/question_type.rb
class QuestionType < ActiveRecord::Base
    has_many :questions
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :alternatives, :through => :answer
  has_many :answers
  has_many :user_exams
  
  validates :name, :presence => true
end

app/models/user_exam.rb
class UserExam < ActiveRecord::Base
  belongs_to :user
  belongs_to :area
  has_many :user_exam_questions, dependent: :destroy
  has_many :questions, through: :user_exam_questions
  #teste
  #accepts_nested_attributes_for :user_exam_questions
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:user_id, :alternative_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/mocks_helper.rb
module MocksHelper
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/user_exams_helper.rb
module UserExamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :alternative_id %><br>
    <%= f.text_field :alternative_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Answers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Alternative</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.user %></td>
        <td><%= answer.alternative %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @answer.user %>
</p>

<p>
  <strong>Alternative:</strong>
  <%= @answer.alternative %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>