config/routes.rb
Rails.application.routes.draw do
  
  get 'user_exam_questions/index'

  get 'user_exam_controller/index'

  resources :user_exams
  mount Ckeditor::Engine => '/ckeditor'
  get 'users/index'

  devise_for :users
  resources :question_types
  resources :answers
  resources :organizers
  resources :institutions
  resources :categories
  resources :areas
  resources :mocks
  resources :mocks do
    resources :exams, except: :index
  end
  
  resources :user_exam do 
    resources :user_exam_questions
  end
  
  
  resources :exams, except: :index
  resources :exams, except: :index do
    resources :questions
  end
  resources :questions do
    resources :helper_objects
    resources :alternatives, except: :index
  end
  resources :helper_objects

  root 'mocks#index'

  match '/users',   to: 'users#index',   via: 'get'
  
  get "user_exam_question/new_custom_question" => 'user_exam_question#new_custom_question', :as => :new_custom_question
  

end

app/models/alternative.rb
class Alternative < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  do_not_validate_attachment_file_type :image
  
  
  # corrigir o erro de validacao de tipo de imagens pois nao esta amigavel ao usuario.
  validates_attachment :image, content_type: { content_type: "image/jpeg" } if present?
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :alternative
end

app/models/area.rb
class Area < ActiveRecord::Base
    has_many :mocks
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :mocks
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  belongs_to :mock
  has_many :questions, dependent: :destroy
end

app/models/helper_object.rb
class HelperObject < ActiveRecord::Base
  
  # referencias
  belongs_to :question
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  do_not_validate_attachment_file_type :image
  
  
  # corrigir o erro de validacao de tipo de imagens pois nao esta amigavel ao usuario.
  validates_attachment :image, content_type: { content_type: "image/jpeg" } if present?
  
end

app/models/institution.rb
class Institution < ActiveRecord::Base
    has_many :mocks
end

app/models/mock.rb
class Mock < ActiveRecord::Base
  belongs_to :institution
  belongs_to :organizer
  belongs_to :category
  belongs_to :area
  has_many :exams, dependent: :destroy
end

app/models/organizer.rb
class Organizer < ActiveRecord::Base
    has_many :mocks
end

app/models/question.rb
class Question < ActiveRecord::Base
  
  # referencias
  belongs_to :exam
  belongs_to :question_type
  has_many :helper_objects, dependent: :destroy
  has_many :alternatives, dependent: :destroy
  has_many :user_exam_questions, dependent: :destroy
  has_many :user_exam, through: :user_exam_questions
  
  validates :number, :exam_id, :veracity, :question_type_id, presence: true

end

app/models/question_type.rb
class QuestionType < ActiveRecord::Base
    has_many :questions
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :alternatives, :through => :answer
  has_many :answers
  has_many :user_exams
  
  validates :name, :presence => true
end

app/models/user_exam.rb
class UserExam < ActiveRecord::Base
  belongs_to :user
  belongs_to :area
  has_many :user_exam_questions, dependent: :destroy
  has_many :questions, through: :user_exam_questions
  #teste
  #accepts_nested_attributes_for :user_exam_questions
end

app/controllers/mocks_controller.rb
class MocksController < ApplicationController
  before_action :set_mock, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # before_filter :require_admin # ativar após criar a tela de usuários comuns
  
  # GET /mocks
  # GET /mocks.json
  def index
    @mocks = Mock.all
  end

  # GET /mocks/1
  # GET /mocks/1.json
  def show
  end

  # GET /mocks/new
  def new
    @mock = Mock.new
  end

  # GET /mocks/1/edit
  def edit
  end

  # POST /mocks
  # POST /mocks.json
  def create
    @mock = Mock.new(mock_params)

    respond_to do |format|
      if @mock.save
        format.html { redirect_to @mock, notice: t("helpers.informations.successfully_created", :model => @mock.model_name.human.titleize) }
        format.json { render :show, status: :created, location: @mock }
      else
        format.html { render :new }
        format.json { render json: @mock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mocks/1
  # PATCH/PUT /mocks/1.json
  def update
    respond_to do |format|
      if @mock.update(mock_params)
        format.html { redirect_to @mock, notice: t('helpers.informations.successfully_updated', model: @mock.model_name.human.titleize) }
        format.json { render :show, status: :ok, location: @mock }
      else
        format.html { render :edit }
        format.json { render json: @mock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mocks/1
  # DELETE /mocks/1.json
  def destroy
    @mock.destroy
    respond_to do |format|
      format.html { redirect_to mocks_url, notice: t("helpers.informations.successfully_destroyed", :model => @mock.model_name.human.titleize) }
      format.json { head :no_content }
    end
  end
  
  def executar
    # começar a bagaça aki
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mock
      @mock = Mock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mock_params
      params.require(:mock).permit(:title, :year, :edition, :application_date, :notice, :institution_id, :organizer_id, :category_id, :area_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/mocks_helper.rb
module MocksHelper
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/user_exams_helper.rb
module UserExamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/mocks/_form.html.erb
<%= form_for @mock, :html => { :class => "form-horizontal mock" } do |f| %>

  <% if @mock.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@mock.errors.count, "error") %> prohibited this mock from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @mock.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :year, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :year, :class => 'form-control' %>
    </div>
    <%=f.error_span(:year) %>
  </div>
  <div class="form-group">
    <%= f.label :edition, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :edition, :class => 'form-control' %>
    </div>
    <%=f.error_span(:edition) %>
  </div>
  <div class="form-group">
    <%= f.label :application_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :application_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:application_date) %>
  </div>
  <div class="form-group">
    <%= f.label :notice, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :notice, :class => 'form-control' %>
    </div>
    <%=f.error_span(:notice) %>
  </div>
  <div class="form-group">
    <%= f.label :institution_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :institution_id, options_for_select(Institution.all.map{ |i| [i.title, i.id]}), :class => 'form-control' %>
    </div>
    <%=f.error_span(:institution_id) %>
  </div>
  <div class="form-group">
    <%= f.label :organizer_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :organizer_id, options_for_select(Organizer.all.map{ |i| [i.title, i.id]}), :class => 'form-control' %>
    </div>
    <%=f.error_span(:organizer_id) %>
  </div>
  <div class="form-group">
    <%= f.label :category_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :category_id, options_for_select(Category.all.map{ |i| [i.title, i.id]}), :class => 'form-control' %>
    </div>
    <%=f.error_span(:category_id) %>
  </div>
  <div class="form-group">
    <%= f.label :area_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :area_id, options_for_select(Area.all.map{ |i| [i.title, i.id]}), :class => 'form-control' %>
    </div>
    <%=f.error_span(:area_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                mocks_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/mocks/edit.html.erb
<%- model_class = Mock -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mocks/index.html.erb
<%- model_class = Mock -%>


<!DOCTYPE html>
<html>

<body>
  <div>
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:id) %></th>
          <th><%= model_class.human_attribute_name(:title) %></th>
          <th><%= model_class.human_attribute_name(:year) %></th>
          <th><%= model_class.human_attribute_name(:edition) %></th>
          <th><%= model_class.human_attribute_name(:application_date) %></th>
          <th><%= model_class.human_attribute_name(:notice) %></th>
          <th><%= model_class.human_attribute_name(:institution_id) %></th>
          <th><%= model_class.human_attribute_name(:organizer_id) %></th>
          <th><%= model_class.human_attribute_name(:category_id) %></th>
          <th><%= model_class.human_attribute_name(:area_id) %></th>
          <th><%= model_class.human_attribute_name(:created_at) %></th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @mocks.each do |mock| %>
          <tr>
            <td><%= mock.id %></td>
            <td><%= link_to mock.title, mock_path(mock) %></td>
            <td><%= mock.year %></td>
            <td><%= mock.edition %></td>
            <td><%= mock.application_date %></td>
            <td><%= mock.notice %></td>
            <td><%= mock.institution.title %></td>
            <td><%= mock.organizer.title %></td>
            <td><%= mock.category.title %></td>
            <td><%= mock.area.title %></td>
            <td><%= mock.created_at.strftime("%d/%m/%Y") %></td>
            <td>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_mock_path(mock), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          mock_path(mock),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem certeza?')) },
                          :class => 'btn btn-xs btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  
    <%= link_to t('.new', :default => t("helpers.links.new")), new_mock_path, :class => 'btn btn-primary' %>
  </div>

<%= content_tag :a, "Teste Modal", href: "#modal", class: 'btn', data: {toggle: 'modal'} %>

      <%= modal_dialog id: "modal",
         header: { show_close: true, dismiss: 'modal', title: 'Modal header' },
         body:   { content: 'This is the body' },
         footer: { content: content_tag(:button, 'Save', class: 'btn') } 
      %>

</body>
<script src="/assets/application-ad5bf39cf1fb0e4b3710fe430c3c9776b68f1a7936e5e14d95559560a4c9ef76.js" data-turbolinks-track="true"></script>

</html>

app/views/mocks/new.html.erb
<%- model_class = Mock -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Novo Simulado'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mocks/show.html.erb
<%- model_class = Mock -%>
  <div class="col-xs-12 col-sm-8 col-md-4">
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
    </div>
    
    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
      <dd><%= @mock.title %></dd>
      <dt><strong><%= model_class.human_attribute_name(:year) %>:</strong></dt>
      <dd><%= @mock.year %></dd>
      <dt><strong><%= model_class.human_attribute_name(:edition) %>:</strong></dt>
      <dd><%= @mock.edition %></dd>
      <dt><strong><%= model_class.human_attribute_name(:application_date) %>:</strong></dt>
      <dd><%= @mock.application_date.strftime("%d/%m/%Y") %></dd>
      <dt><strong><%= model_class.human_attribute_name(:notice) %>:</strong></dt>
      <dd><%= @mock.notice %></dd>
      <dt><strong><%= model_class.human_attribute_name(:institution_id) %>:</strong></dt>
      <dd><%= @mock.institution.title %></dd>
      <dt><strong><%= model_class.human_attribute_name(:organizer_id) %>:</strong></dt>
      <dd><%= @mock.organizer.title %></dd>
      <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
      <dd><%= @mock.category.title %></dd>
      <dt><strong><%= model_class.human_attribute_name(:area_id) %>:</strong></dt>
      <dd><%= @mock.area.title %></dd>
    </dl>
    
    <%= link_to t('.back', :default => t("helpers.links.back")),
                  mocks_path, :class => 'btn btn-default'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_mock_path(@mock), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  mock_path(@mock),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
    </div>
  <div class="col-xs-12 col-sm-8 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="text-center">
          Listagem das Provas
        </div>
      </div>
      <div class="panel-body panel-lg">
        <% @mock.exams.each do |e| %>
          <% if e.title %>
            <p>
              <h2><%= link_to e.title, exam_path(e) %></h2>
            </p>
          <% end %>
        <% end %>
      </div>
      <div class="panel-footer panel-lg">
        <%= form_for([@mock, @mock.exams.build], :html => {:class => 'form-inline'}) do |f|  %>
          <div class="form-group">
            <%= f.text_field :title, :class => 'form-control', :placeholder => "Nova Prova" %>
          </div>
          <%= f.submit :class => 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>