config/routes.rb
Rails.application.routes.draw do
  
  get 'user_exam_questions/index'

  get 'user_exam_controller/index'

  resources :user_exams
  mount Ckeditor::Engine => '/ckeditor'
  get 'users/index'

  devise_for :users
  resources :question_types
  resources :answers
  resources :organizers
  resources :institutions
  resources :categories
  resources :areas
  resources :mocks
  resources :mocks do
    resources :exams, except: :index
  end
  
  resources :user_exam do 
    resources :user_exam_questions
  end
  
  
  resources :exams, except: :index
  resources :exams, except: :index do
    resources :questions
  end
  resources :questions do
    resources :helper_objects
    resources :alternatives, except: :index
  end
  resources :helper_objects

  root 'mocks#index'

  match '/users',   to: 'users#index',   via: 'get'
  
  get "user_exam_question/new_custom_question" => 'user_exam_question#new_custom_question', :as => :new_custom_question
  

end

app/models/alternative.rb
class Alternative < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  do_not_validate_attachment_file_type :image
  
  
  # corrigir o erro de validacao de tipo de imagens pois nao esta amigavel ao usuario.
  validates_attachment :image, content_type: { content_type: "image/jpeg" } if present?
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :alternative
end

app/models/area.rb
class Area < ActiveRecord::Base
    has_many :mocks
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :mocks
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  belongs_to :mock
  has_many :questions, dependent: :destroy
end

app/models/helper_object.rb
class HelperObject < ActiveRecord::Base
  
  # referencias
  belongs_to :question
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  do_not_validate_attachment_file_type :image
  
  
  # corrigir o erro de validacao de tipo de imagens pois nao esta amigavel ao usuario.
  validates_attachment :image, content_type: { content_type: "image/jpeg" } if present?
  
end

app/models/institution.rb
class Institution < ActiveRecord::Base
    has_many :mocks
end

app/models/mock.rb
class Mock < ActiveRecord::Base
  belongs_to :institution
  belongs_to :organizer
  belongs_to :category
  belongs_to :area
  has_many :exams, dependent: :destroy
end

app/models/organizer.rb
class Organizer < ActiveRecord::Base
    has_many :mocks
end

app/models/question.rb
class Question < ActiveRecord::Base
  
  # referencias
  belongs_to :exam
  belongs_to :question_type
  has_many :helper_objects, dependent: :destroy
  has_many :alternatives, dependent: :destroy
  has_many :user_exam_questions, dependent: :destroy
  has_many :user_exam, through: :user_exam_questions
  
  validates :number, :exam_id, :veracity, :question_type_id, presence: true

end

app/models/question_type.rb
class QuestionType < ActiveRecord::Base
    has_many :questions
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :alternatives, :through => :answer
  has_many :answers
  has_many :user_exams
  
  validates :name, :presence => true
end

app/models/user_exam.rb
class UserExam < ActiveRecord::Base
  belongs_to :user
  belongs_to :area
  has_many :user_exam_questions, dependent: :destroy
  has_many :questions, through: :user_exam_questions
  #teste
  #accepts_nested_attributes_for :user_exam_questions
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_filter :require_admin
  
  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @mock = Mock.find(params[:mock_id])
    @exam = @mock.exams.create(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: t("helpers.informations.successfully_created", model: @exam.model_name.human.titleize) }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: t("helpers.informations.successfully_updated", :model => @exam.model_name.human.titleize) }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    mock = @exam.mock
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to mock, notice: t("helpers.informations.successfully_destroyed", :model => @exam.model_name.human.titleize) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:title, :mock_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/mocks_helper.rb
module MocksHelper
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/user_exams_helper.rb
module UserExamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exams/_form.html.erb
<%= form_for @exam, :html => { :class => "form-horizontal exam" } do |f| %>

  <% if @exam.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @exam.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  
 
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
               @exam.mock, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/exams/edit.html.erb
<%- model_class = Exam -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/exams/index.html.erb
<%- model_class = Exam -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:mock_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= link_to exam.id, exam_path(exam) %></td>
        <td><%= exam.title %></td>
        <td><%= exam.mock_id %></td>
        <td><%=l exam.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_exam_path(exam), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      exam_path(exam),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_exam_path,
            :class => 'btn btn-primary' %>

app/views/exams/new.html.erb
<%- model_class = Exam -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/exams/show.html.erb
<%- model_class = Exam -%>
  <div class="col-xs-12 col-sm-8 col-md-4">
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
    </div>
    <dl class="dl-horizontal" style="font-size:20px;">
      <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
      <dd><%= @exam.title %></dd>
      <dt><strong><%= model_class.human_attribute_name(:mock_id) %>:</strong></dt>
      <dd><%= @exam.mock.title %></dd>
    </dl>
    
    <%= link_to t('.back', :default => t("helpers.links.back")),
                  mock_path(@exam.mock), :class => 'btn btn-default'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_exam_path(@exam), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  exam_path(@exam),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
  </div>
  <div class="col-xs-12 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="text-center">Questões</div>
      </div>
      <div class="panel-body panel-lg">
        <% @exam.questions.order("number ASC").in_groups_of(6, false) do |group| %>
          <div class='btn-group btn-group-justified'>
            <% group.each do |helper| %>
              <% if helper.id %>
                <%= link_to helper.number, question_path(helper), :class => 'btn btn-default', :role =>'button'  %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="panel-footer panel-lg">
        <h2 class="text-center">Adicionar questão</h2>
        <%= form_for([@exam, @exam.questions.build]) do |f| %>
          <table class="table">
            <tr>
              <td><%= f.label :number %></td>
              <td><%= f.number_field :number, :class => 'form-control', :placeholder => "Nº" %></td>
            </tr>
            <tr>
              <td><%= f.label :question_type_id, "Tipo de Questão" %></td>
              <td><%= f.select :question_type_id, options_for_select(QuestionType.all.map{ |i| [i.title, i.id]}), :class => 'form-control' %></td>
            </tr>
            <tr>
              <td><%= f.label :veracity, "Avaliar como Verdadeira?" %></td>
              <td><%= f.check_box :veracity %></td>
            </tr>
            <tr>
              <td><%= f.label :title, "Título" %></td>
              <td><%= f.cktext_area :title %></td>
            </tr>
          </table>
          <%= f.submit :class => 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>