config/routes.rb
Rails.application.routes.draw do
  
  get 'user_exam_questions/index'

  get 'user_exam_controller/index'

  resources :user_exams
  mount Ckeditor::Engine => '/ckeditor'
  get 'users/index'

  devise_for :users
  resources :question_types
  resources :answers
  resources :organizers
  resources :institutions
  resources :categories
  resources :areas
  resources :mocks
  resources :mocks do
    resources :exams, except: :index
  end
  
  resources :user_exam do 
    resources :user_exam_questions
  end
  
  
  resources :exams, except: :index
  resources :exams, except: :index do
    resources :questions
  end
  resources :questions do
    resources :helper_objects
    resources :alternatives, except: :index
  end
  resources :helper_objects

  root 'mocks#index'

  match '/users',   to: 'users#index',   via: 'get'
  
  get "user_exam_question/new_custom_question" => 'user_exam_question#new_custom_question', :as => :new_custom_question
  

end

app/models/alternative.rb
class Alternative < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  do_not_validate_attachment_file_type :image
  
  
  # corrigir o erro de validacao de tipo de imagens pois nao esta amigavel ao usuario.
  validates_attachment :image, content_type: { content_type: "image/jpeg" } if present?
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :alternative
end

app/models/area.rb
class Area < ActiveRecord::Base
    has_many :mocks
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :mocks
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  belongs_to :mock
  has_many :questions, dependent: :destroy
end

app/models/helper_object.rb
class HelperObject < ActiveRecord::Base
  
  # referencias
  belongs_to :question
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  do_not_validate_attachment_file_type :image
  
  
  # corrigir o erro de validacao de tipo de imagens pois nao esta amigavel ao usuario.
  validates_attachment :image, content_type: { content_type: "image/jpeg" } if present?
  
end

app/models/institution.rb
class Institution < ActiveRecord::Base
    has_many :mocks
end

app/models/mock.rb
class Mock < ActiveRecord::Base
  belongs_to :institution
  belongs_to :organizer
  belongs_to :category
  belongs_to :area
  has_many :exams, dependent: :destroy
end

app/models/organizer.rb
class Organizer < ActiveRecord::Base
    has_many :mocks
end

app/models/question.rb
class Question < ActiveRecord::Base
  
  # referencias
  belongs_to :exam
  belongs_to :question_type
  has_many :helper_objects, dependent: :destroy
  has_many :alternatives, dependent: :destroy
  has_many :user_exam_questions, dependent: :destroy
  has_many :user_exam, through: :user_exam_questions
  
  validates :number, :exam_id, :veracity, :question_type_id, presence: true

end

app/models/question_type.rb
class QuestionType < ActiveRecord::Base
    has_many :questions
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :alternatives, :through => :answer
  has_many :answers
  has_many :user_exams
  
  validates :name, :presence => true
end

app/models/user_exam.rb
class UserExam < ActiveRecord::Base
  belongs_to :user
  belongs_to :area
  has_many :user_exam_questions, dependent: :destroy
  has_many :questions, through: :user_exam_questions
  #teste
  #accepts_nested_attributes_for :user_exam_questions
end

app/controllers/user_exams_controller.rb
class UserExamsController < ApplicationController
  before_action :set_user_exam, only: [:show, :edit, :update, :destroy]

  # GET /user_exams
  # GET /user_exams.json
  def index
    @user_exams = UserExam.all
  end

  # GET /user_exams/1
  # GET /user_exams/1.json
  def show
  end

  # GET /user_exams/new
  def new
    @user_exam = UserExam.new
  end

  # GET /user_exams/1/edit
  def edit
  end

  # POST /user_exams
  # POST /user_exams.json
  def create
    @user_exam = UserExam.new(user_exam_params)
    @user_exam.user_id = current_user.id

    respond_to do |format|
      if @user_exam.save
        format.html { redirect_to @user_exam, notice: 'User exam was successfully created.' }
        format.json { render :show, status: :created, location: @user_exam }
      else
        format.html { render :new }
        format.json { render json: @user_exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_exams/1
  # PATCH/PUT /user_exams/1.json
  def update
    respond_to do |format|
      if @user_exam.update(user_exam_params)
        format.html { redirect_to @user_exam, notice: 'User exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_exam }
      else
        format.html { render :edit }
        format.json { render json: @user_exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_exams/1
  # DELETE /user_exams/1.json
  def destroy
    @user_exam.destroy
    respond_to do |format|
      format.html { redirect_to user_exams_url, notice: 'User exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_exam
      @user_exam = UserExam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_exam_params
      params.require(:user_exam).permit(:title, :user_id, :area_id, :date_application)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/mocks_helper.rb
module MocksHelper
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/user_exams_helper.rb
module UserExamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_exams/_form.html.erb
<%= form_for @user_exam, :html => { :class => "form-horizontal user_exam" } do |f| %>

  <% if @user_exam.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user_exam.errors.count, "error") %> prohibited this user_exam from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user_exam.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :area_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :area_id, options_for_select(Area.all.map{ |i| [i.title, i.id]}), :class => 'form-control' %>
    </div>
    <%=f.error_span(:area_id) %>
  </div>
  <div class="form-group">
    <%= f.label :date_application, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_field(:date_application, :class => 'form-control') %>
    </div>
    <%=f.error_span(:date_application) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_exams_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/user_exams/edit.html.erb
<%- model_class = UserExam -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_exams/index.html.erb
<%- model_class = UserExam -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:area_id) %></th>
      <th><%= model_class.human_attribute_name(:date_application) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @user_exams.each do |user_exam| %>
      <tr>
        <td><%= link_to user_exam.id, user_exam_path(user_exam) %></td>
        <td><%= user_exam.title %></td>
        <td><%= user_exam.user_id %></td>
        <td><%= user_exam.area_id %></td>
        <td><%= user_exam.date_application %></td>
        <td><%=l user_exam.created_at %></td>
        <td>
          <%= link_to edit_user_exam_path(user_exam), class: 'btn btn-default btn-xs' do %>
            <i class="glyphicon glyphicon-pencil"></i>
          <% end %>
          <%= link_to user_exam_path(user_exam),
                      method: :delete,
                      data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
                      class: 'btn btn-xs btn-default' do %>
            <i class="glyphicon glyphicon-remove-circle"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_exam_path,
            :class => 'btn btn-primary' %>

app/views/user_exams/new.html.erb
<%- model_class = UserExam -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_exams/show.html.erb
<%- model_class = UserExam -%>
<div class="container-fluid">
  <div class="row">
    <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
        
        
    </nav>

    <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
      <br>
      <div class="col-sm-12">
        <div class="row text-right">
          <%= link_to user_exams_path, class: 'btn btn-xs btn-default' do %>
            <i class="glyphicon glyphicon-arrow-left"></i>
          <% end %>
          <%= link_to edit_user_exam_path(@user_exam), class: 'btn btn-xs btn-default' do %>
            <i class="glyphicon glyphicon-pencil"></i>
          <% end %>
          <%= link_to user_exam_path(@user_exam),
                      :method => 'delete',
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-default' do %>
            <i class="glyphicon glyphicon-remove-circle"></i>
          <% end %>
        </div>
      </div>
      <div class="col-sm-12" id="cabecalho">
        <div class="row text-center placeholders">
          <table class="table">
            <tr>
              <th class="small-column"><%= t('activerecord.models.user_exam.one') %>:</th>
              <th class="large-column"><%= @user_exam.title %></th>
            </tr>
            <tr>
              <th class="small-column"><%= t('activerecord.attributes.user_exam.user_id') %>:</th>
              <th class="large-column"><%= @user_exam.user.name %></th>
            </tr>
            <tr>
              <th class="small-column"><%= t('activerecord.attributes.user_exam.area_id') %>:</th>
              <th class="large-column"><%= @user_exam.area.title %></th>
            </tr>
            <tr>
              <th class="small-column"><%= t('activerecord.attributes.user_exam.date_application') %>:</th>
              <th class="large-column"><%= l @user_exam.date_application, format: :long %></th>
            </tr>
          </table>
        </div>
      </div>

      <div class="col-sm-12">
        <h3><%= t('activerecord.models.user_exam_question.others') %></h3>
        <br>
        <% @user_exam.user_exam_questions.each do |user_exam_question| %>
          <div style="border:1px solid black; padding-bottom: 0.5cm;" class="col-sm-11"> <!-- corrigir essa borda -->
            <div id='question'>
              <div class="col-sm-1">
                <h4 class='align-middle'><%= user_exam_question.order %></h4>
              </div>
              <div class="col-sm-11">
                <small class="pull-right"><%= user_exam_question.question.exam.mock.title %></small>
                <h1><%= raw user_exam_question.question.title %></h1>
              </div>
            </div>
            <div id='answers'>
              <% user_exam_question.question.alternatives.each_with_index do |alternative, index | %>
                <div class='col-sm-1'>
                  <%= index + 1 %>
                </div>
                <div class='col-sm-11'>
                  <%= raw alternative.title %>
                </div>
              <% end %>
            </div>
          </div>
          <div class="col-sm-1">

          </div>
        <% end %>
      </div>
    </main>
    
  </div>
</div>

    